# Cors configuration for the front


# Database properties including access for PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuration de la journalisation (logging)
logging.level.root=error
logging.level.com.thghpi.bandapp=DEBUG
logging.level.org.springframework.data=INFO
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# Swagger configuration - to disable it in production
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# jwt properties
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME}

# Password strength requirements
app.password.min-length=${PASSWORD_MIN_LENGTH}
app.password.max-length=${PASSWORD_MAX_LENGTH}
app.password.regex=${PASSWORD_REGEX}
app.password.require-uppercase=${PASSWORD_REQUIRE_UPPERCASE}
app.password.require-lowercase=${PASSWORD_REQUIRE_LOWERCASE}
app.password.require-digit=${PASSWORD_REQUIRE_DIGIT}
app.password.require-special-character=${PASSWORD_REQUIRE_SPECIAL_CHARACTER}

# Password encoder strength
app.password-encoder.strength=${PASSWORD_ENCODER_STRENGTH}