# api name
spring.application.name=band-api

# server port where the api is exposed
server.port=8081

# Spring profile to use
spring.profiles.active=${SPRING_PROFILE}

# jwt properties
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME}