# api name
spring.application.name=band-api

# server port where the api is exposed
server.port=8080

# Cors configuration for the front
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200}

# Spring profile to use
spring.profiles.active=${SPRING_PROFILE_ACTIVE:dev}

# Database properties
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate common property - can be disabled
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
